@startuml eric 

actor Utilisateur as U
participant HomePage as HP
participant Navigation as N

U -> HP: Accéder à la page d'accueil
activate HP
HP --> U: Afficher la page d'accueil

U -> HP: Appuyer sur "Jouer au Morpion contre un ami"
activate N
HP --> N: Naviguer vers Morpion avec ami
deactivate N

U -> HP: Appuyer sur "Jouer au Morpion contre le téléphone"
activate N
HP --> N: Naviguer vers Morpion avec téléphone
deactivate N

U -> HP: Appuyer sur "Inscription"
activate N
HP --> N: Naviguer vers Inscription
deactivate N

U -> HP: Appuyer sur "Connexion"
activate N
HP --> N: Naviguer vers Connexion
deactivate N

@enduml
